### ISSUE TITLE
Network Critical Error 

### ISSUE THREAD

**Issue by dtarrant2019** [walking-octopus/system-info-ut#10]
Just ran Ubuntu Info on my OP5t and the Network Panel reported Critical Error. However wifi and phone calls are working fine.
I'm running xenial stable OTA-25.
Don't remember having this problem prior to upgrading.

**Comment by aparatext** [comment]
Hmm. That's weird.

This error indicates that the Python side had raised an exception. Can you please share the logs at that point? You can use the [LogViewer](https://open-store.io/app/logviewer.ruditimmer) app to copy them.

**Comment by dtarrant2019** [comment]
file:///home/phablet/.cache/copytoclipboard.costales/HubIncoming/1/application-click-logviewer.ruditimmer_logviewer_2.6.0.log

file:///home/phablet/.cache/copytoclipboard.costales/HubIncoming/2/application-legacy-morph-browser-.log

file:///home/phablet/.cache/copytoclipboard.costales/HubIncoming/3/dbus.log

**Comment by dtarrant2019** [comment]
Not sure what I was doing as I've never done this before. Hope it will be of some use.
(Just noticed the same issue on my Nexus-4 after upgade to OTA-25)

**Comment by dtarrant2019** [comment]
Hi, I fired up LogViewer and posted the files it produced on GitHub.
Never done this before, so not sure if I did it right. Have a look and let me know what you think.

Regards, David

Sent from Samsung Galaxy-A51 Powered by Three
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dtarrant2019** [comment]
Where is walking-octopus ? I understand he is from Ukraine. I hope he is ok.

**Comment by aparatext** [comment]
I'm fine, just was a little busy with the exams. Sorry for letting this issue slip out of my mind.

I tried updating my Nexus 5 to the latest RC, but I couldn't replicate the bug. Can you please send the log files? Your last message only contained the paths to some unrelated logs... The logs are probably in a file like `/home/phablet/.cache/upstart/application-click-system-info.walking-octopus_system-info_1.1.0.log`.

If I had to guess what went wrong, I might put the blame on NetworkManager. That part of the code in general is quite unreliable, just executing some commands and using RegExp to get to the values.

**Comment by dtarrant2019** [comment]
Hope your exams went well.
Just looked for the log on my OP5t with file manager, but can't find it. Maybe I need to use terminal? Trouble is I'm not very experienced and I'm afraid of breaking the system. The sim in that device enables long duration calls at very low rates and my wife uses it for calling her sister.
I'm 81 years old, so you aren't dealing with a computer wiz-kid. 😒

Sent from Samsung Galaxy-A51 Powered by Three
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dtarrant2019** [comment]
Just had an idea, Ubuntu Info is on my old Nexus-4, so powered it on, but no critical error msg. I guess this is because it doesn't have a sim.

Sent from Samsung Galaxy-A51 Powered by Three
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aparatext** [comment]
> Hope your exams went well.

Thanks!

>  Just looked for the log on my OP5t with file manager, but can't find it. Maybe I need to use terminal? Trouble is I'm not very experienced and I'm afraid of breaking the system. The sim in that device enables long duration calls at very low rates and my wife uses it for calling her sister. I'm 81 years old, so you aren't dealing with a computer wiz-kid.

Don't worry! Those are just the logs, so even if you delete them, nothing bad will come of it.

 - If you're in the logs folder and don't see any such a file, maybe the logs just got deleted after some period of not opening the app. Just reopening the app would help then. 

 - If you're in the File Manager at your home folder and can't find `.cache`, just turn on the "Show hidden files" option from that settings popup. The icon for it is in the header, second from the right corner. You'd also need to press "Unlock" to give it permission to see more than the standard directories.

 - If you find it easier, you can just copy this command to copy this file into Downloads: `cat ~/.cache/upstart/*system-info.walking-octopus*.log > ~/Downloads/appLogs.txt`.

**Comment by dtarrant2019** [comment]
Sending this from my OP5t. As you suggested, just restarted Ubuntu Info and now there is no Network Critical Error msg! Seems there is no problem after all. Sorry for wasting your time.

**Comment by aparatext** [comment]
No problem. In general, this part of the app is flaky, so I wasn't surprised it was the one to break... Thanks for reporting these weird bugs, even if we weren't able to reproduce them.
