### ISSUE TITLE
[feature] More detailed hardware usage

### ISSUE THREAD

**Issue by gbdomubpkm** [walking-octopus/system-info-ut#2]
Hello. Thank you for this great app.
The hardware usage part interests me most, in my case, how my Volla works.

 - [x] It would be great if you could add detail to this category, like the breakdown of RAM and CPU usage by process/app.
 - [x] The RAM usage percentage seems wrong: here's the [screenshoot](https://user-images.githubusercontent.com/50362604/188924952-6607ad48-713e-4694-ad0c-7d92fdd50f32.png).

Thank you in advance for considering the idea.

**Comment by aparatext** [comment]
Hi! I'm glad you found this app useful. If you don't mind, I reformatted your issue into a checklist. If I misunderstood anything, let me know!
 - If I understood you correctly, you suggest a page with a list of processes sorted by their RAM/CPU usage and/or a quick view of the most resource-hungry processes. That would be an amazing feature I haven't yet considered!
 - The difference between memory usage percentage and free/total memory is a bug that you caught. Seems like I might have accidentally counted RAM used by kernel cache as used.
I'll reach back to you tomorrow. I'm glad to receive feedback for this tittle tool.

**Comment by gbdomubpkm** [comment]
In fact, everything related to memory usage is interesting and can be a useful tool to understand why there is a crash if several apps or webapps are open at the same time, for example. In addition, I noticed that launching a webapp made with webber significantly increased the RAM used, so several webapps at the same time.... You are talking about RAM /CPU per process (that's a great idea), I  talked first about RAM per app or webapp. I don't know if it is exactly the same thing but your way is good.

**Comment by aparatext** [comment]
All apps have a process with a matching name, but not all processes are user-facing apps. I tried, but I haven't come up with a way to filter it to only show user-facing apps. So, I'll just start working on a built-in task manager.

**Comment by aparatext** [comment]
Looks like I found the source of this issue.
https://github.com/giampaolo/psutil/issues/685#issuecomment-202914057

**Comment by aparatext** [comment]
I've added a built-in task manager to it. It supports viewing, killing, sorting, and filtering processes in a convenient user-friendly UI. You can help test it by downloading the latest build from the CI [here](https://github.com/walking-octopus/system-info-ut/actions/runs/3032082100)

**Comment by gbdomubpkm** [comment]
Hello.
I just downloaded the trial click. Thank you for this great work. Everything seems to be working fine visually and indeed user friendly but I will continue with my overview.

**Comment by gbdomubpkm** [comment]
In CPU info, see temperature !
![screenshot20220911_174545024](https://user-images.githubusercontent.com/50362604/189536730-a76ba813-3e05-4b9d-8a83-e57dd51e464e.png)

**Comment by gbdomubpkm** [comment]
Great task manager and it seems working nice. About visual reading, maybe improve a little comfort with 2 distinct columns aligned for all CPU RAM processes?
The sort order is not persistent after restarting the app. Is it wanted?
That's it for the task manager.

**Comment by aparatext** [comment]
> In CPU info, see temperature!

It's the temperature for the first CPU core. Also, I've just made it automatically convert to ℃, so it would be more readable.

> Maybe improve a little comfort with 2 distinct columns

I'm afraid the dedicated columns would be difficult to implement.

> The sort order is not persistent after restarting the app.

I didn't make this into a persistent setting. Though if you want to, I might add it.

Overall, does the task manager feel comfortable to use?
 - Can you quickly see the resource consumption of some app, find info on a particular process, or kill some app?
 - Does it refresh too fast or too slow? Some users reported that killing a process while sorting by CPU is inconvenient due to the fast refresh time.
 - Should I add PIDs or would it be useless in most cases?

**Comment by gbdomubpkm** [comment]
Hello.

I just tested: i saw that webapps (web-app container) consume a lot of RAM indeed 😉

The info reports are updated and are done in an adequate time I think.

I will be for the sorting options to remain persistent, including when you exit the task manager, which is not currently the case.

PIDs : sorry i don't know what is the meaning. But if it can be useful...

**However**, I often see a critical error (bar appearing at the bottom of the screen) when exiting the task manager after changing the sort order.

**Comment by aparatext** [comment]
> However, I often see a critical error (bar appearing at the bottom of the screen) when exiting the task manager after changing the sort order.

It means the app crashed internally several times, Please share the logs, so I can debug this issue. Use an app like [Logviewer](https://open-store.io/app/logviewer.neothethird) to do it.

**Comment by gbdomubpkm** [comment]
library "libpq_cust.so" not found
Creating a QMirClientScreen now
Got library name:  "/usr/lib/aarch64-linux-gnu/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
[PERFORMANCE]: Last frame took 107 ms to render.
[PERFORMANCE]: Last frame took 52 ms to render.
qml: Python error: file:///opt/click.ubuntu.com/system-info.walking-octopus/1.0.3/qml/Pages/Categories/TaskManager.qml:34: TypeError: Type error
qml: Python error: file:///opt/click.ubuntu.com/system-info.walking-octopus/1.0.3/qml/Pages/Categories/TaskManager.qml:34: TypeError: Type error
qml: Python error: file:///opt/click.ubuntu.com/system-info.walking-octopus/1.0.3/qml/Pages/Categories/TaskManager.qml:34: TypeError: Type error
QObject::startTimer: Timers cannot be started from another thread

**Comment by aparatext** [comment]
Fixed!

**Comment by aparatext** [comment]
I think I should close this issue. The memory information is now more accurate and a task manager is ready and functioning.
