### ISSUE TITLE
Make sort options in task manager persistent

### ISSUE THREAD

**Issue by kugiigi** [walking-octopus/system-info-ut#7]
### Description
It would be good if the sorting options in the task manager are persistent or at least an option to make them persistent.

**Comment by aparatext** [comment]
Done! Now the sorting options will be persistent.

**Comment by gbdomubpkm** [comment]
Please, add the choice 'Exit' (without save) in the sorting options.

**Comment by gbdomubpkm** [comment]
Not persistent on V 1.1.0 on Volla.

**Comment by aparatext** [comment]
> Not persistent on V 1.1.0 on Volla.

I haven't yet published a new release yet. If you wish, you can download the latest build [here](https://github.com/walking-octopus/system-info-ut/actions/runs/3149722493).

**Comment by gbdomubpkm** [comment]
> > Not persistent on V 1.1.0 on Volla.
> 
> I haven't yet published a new release. If you wish, you can download the latest build [here](https://github.com/walking-octopus/system-info-ut/actions/runs/3149722493).

Thank you. I put the comment because, in fact, i was not sure of the release. 😉

**Comment by aparatext** [comment]
> Please, add the choice 'Exit' (without saving) in the sorting options.

I'll look into if it's possible to detect clicks outside a dialog. I think it would be somewhat intuitive and won't clutter the UI.

**Comment by gbdomubpkm** [comment]
> > Please, add the choice 'Exit' (without saving) in the sorting options.
> 
> I'll look into if it's possible to detect clicks outside a dialog. I think it would be somewhat intuitive and won't clutter the UI.

In fact, it is lighter. I was simply highlighting the idea of ​​being able to exit the dialog box without saving.
